eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka


spring:
  cloud:
    config:
      override-system-properties: false